name: Auto Update and Push

# Trigger on manual workflow dispatch
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make a change to a file (e.g., update a README with a timestamp)
      - name: Make Change
        run: |
          echo "Last updated: $(date)" >> README.md

      # Step 3: Commit the changes
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update README with timestamp"

      # Step 4: Push the changes back to GitHub
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
